CREATE TABLE `users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `second_name` VARCHAR(255) NOT NULL,
  `age` TINYINT(10) UNSIGNED NOT NULL,
  `sex` CHAR(1) NOT NULL
) ENGINE=InnoDB CHARSET=utf8;
